"""Implementing #2212

Revision ID: 3f6a0c249469
Revises: 
Create Date: 2016-12-17 15:26:06.775031

"""

# revision identifiers, used by Alembic.
import sideboard

revision = '3f6a0c249469'
down_revision = '49c6c2987ae5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('updated', sideboard.lib.sa.UTCDateTime(),
                                    server_default=sa.text("timezone('utc', current_timestamp)"),
                                    onupdate=sa.text("timezone('utc', current_timestamp)"), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'updated')
    ### end Alembic commands ###
